#!/data/data/com.termux/files/usr/bin/bash
#
# TermuxFM installer for native Termux on Android.
#
# Installs no packages, needs no root, and compiles nothing: the whole
# application is pure-stdlib Python, so installation is a file copy plus a
# termux-services service directory.

set -euo pipefail

APP_NAME="termuxfm"
SERVICE_NAME="filemanager"
DEFAULT_PORT=8080
TERMUX_PREFIX="/data/data/com.termux/files/usr"

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OPT_DIR=""
BIN_PATH=""
SERVICE_DIR=""
LOG_DIR=""

bold()  { printf '\033[1m%s\033[0m\n' "$*"; }
info()  { printf '  %s\n' "$*"; }
ok()    { printf '\033[32m  ok\033[0m %s\n' "$*"; }
warn()  { printf '\033[33m  !!\033[0m %s\n' "$*" >&2; }
die()   { printf '\033[31merror:\033[0m %s\n' "$*" >&2; exit 1; }

step() { printf '\n'; bold "$*"; }

# ── 1. environment checks ──────────────────────────────────────────────

check_termux() {
  step "Checking the environment"

  if [ -z "${PREFIX:-}" ]; then
    die "PREFIX is not set. Run this inside Termux, not over adb shell or in a
       proot/Debian container."
  fi
  if [ "$PREFIX" != "$TERMUX_PREFIX" ]; then
    die "PREFIX is '$PREFIX' but native Termux uses '$TERMUX_PREFIX'.
       This looks like proot-distro, Andronix or another container.
       TermuxFM is built for NATIVE Termux."
  fi
  ok "native Termux ($PREFIX)"

  OPT_DIR="$PREFIX/opt/$APP_NAME"
  BIN_PATH="$PREFIX/bin/$SERVICE_NAME"
  SERVICE_DIR="$PREFIX/var/service/$SERVICE_NAME"
  LOG_DIR="$PREFIX/var/log/$SERVICE_NAME"

  if [ "$(id -u)" = "0" ]; then
    die "Do not run this as root. Run it as your normal Termux user."
  fi
  ok "not running as root"

  local arch
  arch="$(uname -m)"
  case "$arch" in
    aarch64|arm64) ok "architecture $arch" ;;
    *) warn "architecture is '$arch', not aarch64. TermuxFM is pure Python so
       this should still work, but it is untested here." ;;
  esac

  # Python: the one hard requirement, and Termux's build targets Bionic.
  if ! command -v python3 >/dev/null 2>&1; then
    die "python3 not found. Install it with:
       pkg install python"
  fi
  local pyver
  pyver="$(python3 -c 'import sys; print("%d.%d" % sys.version_info[:2])')"
  if ! python3 -c 'import sys; sys.exit(0 if sys.version_info >= (3, 9) else 1)'; then
    die "Python $pyver is too old; 3.9 or newer is required.
       Update it with:  pkg upgrade python"
  fi
  ok "python3 $pyver ($(command -v python3))"

  # Confirm the stdlib modules we depend on are all present in this build.
  if ! python3 - <<'PY' >/dev/null 2>&1
import hashlib, hmac, http.server, json, mimetypes, os, secrets
import socketserver, threading, unicodedata, zipfile
hashlib.pbkdf2_hmac("sha256", b"x", b"y", 1)
PY
  then
    die "This Python build is missing modules TermuxFM needs (hashlib/ssl
       support may be broken). Try:  pkg reinstall python"
  fi
  ok "required stdlib modules present"

  if ! command -v sv >/dev/null 2>&1; then
    die "termux-services is not installed. Install it with:
       pkg install termux-services
     then restart Termux so the service supervisor starts."
  fi
  ok "termux-services ($(command -v sv))"
}

check_storage() {
  step "Checking storage access"
  if [ ! -d "$HOME/storage/shared" ]; then
    warn "$HOME/storage/shared does not exist."
    warn "Run 'termux-setup-storage' and grant the permission, then re-run this
       installer. Continuing with a different --root is also fine."
  else
    ok "shared storage available ($HOME/storage/shared)"
  fi
}

# ── 2. install files ───────────────────────────────────────────────────

install_files() {
  step "Installing application files"
  [ -f "$REPO_DIR/termuxfm/cli.py" ] || die "cannot find termuxfm/ in $REPO_DIR"
  [ -f "$REPO_DIR/web/index.html" ] || die "cannot find web/ in $REPO_DIR"

  mkdir -p "$OPT_DIR"
  # Replace the code outright so a removed file does not linger.
  rm -rf "$OPT_DIR/termuxfm" "$OPT_DIR/web"
  cp -r "$REPO_DIR/termuxfm" "$OPT_DIR/termuxfm"
  cp -r "$REPO_DIR/web" "$OPT_DIR/web"
  find "$OPT_DIR" -name '__pycache__' -type d -prune -exec rm -rf {} + 2>/dev/null || true
  ok "code installed to $OPT_DIR"

  cat > "$BIN_PATH" <<EOF
#!$PREFIX/bin/sh
# TermuxFM launcher (generated by install-termux.sh)
PYTHONPATH="$OPT_DIR\${PYTHONPATH:+:\$PYTHONPATH}"
export PYTHONPATH
exec python3 -u -m termuxfm "\$@"
EOF
  chmod 755 "$BIN_PATH"
  ok "launcher installed as $BIN_PATH"
}

# ── 3. storage layout ──────────────────────────────────────────────────

create_tree() {
  step "Preparing the server directory"
  local root="${ROOT_DIR:-$HOME/storage/shared/Server}"
  if [ ! -d "$root" ]; then
    mkdir -p "$root" || die "could not create $root"
    ok "created $root"
  else
    ok "using existing $root"
  fi
  # Only create what is missing; never touch existing content.
  local sub
  for sub in downloads/torrents downloads/direct media/movies media/tv; do
    if [ ! -d "$root/$sub" ]; then
      mkdir -p "$root/$sub" && info "created $sub/"
    fi
  done
  ROOT_DIR="$root"
}

# ── 4. port check ──────────────────────────────────────────────────────

check_port() {
  step "Checking port $PORT"
  if python3 - "$PORT" <<'PY'
import socket, sys
port = int(sys.argv[1])
sock = socket.socket()
sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
try:
    sock.bind(("0.0.0.0", port))
except OSError:
    sys.exit(1)
finally:
    sock.close()
PY
  then
    ok "port $PORT is free"
  else
    warn "port $PORT is already in use."
    warn "If that is an old TermuxFM, this is fine (it will restart)."
    warn "Otherwise re-run with:  ./scripts/install-termux.sh --port <other>"
  fi
}

# ── 5. credentials ─────────────────────────────────────────────────────

configure() {
  step "Configuring TermuxFM"
  local config="${CONFIG_PATH:-$HOME/.config/$APP_NAME/config.json}"
  local args=(--config "$config" --root "$ROOT_DIR" --host "$HOST" --port "$PORT")

  if [ -f "$config" ] && [ "${FORCE_SETUP:-0}" != "1" ]; then
    ok "keeping the existing config at $config"
    info "change the password later with:  $SERVICE_NAME passwd"
  else
    info "Choose the username and password for the web interface."
    info "(the password is stored only as a PBKDF2 hash, never in plain text)"
    printf '\n'
    "$BIN_PATH" setup "${args[@]}" ${FORCE_SETUP:+--force} \
      || die "setup did not complete; re-run:  $SERVICE_NAME setup"
  fi
  CONFIG_PATH="$config"

  # Fail now, not at boot, if anything is inconsistent.
  "$BIN_PATH" check --config "$CONFIG_PATH" >/dev/null \
    || die "configuration check failed; run:  $SERVICE_NAME check"
  ok "configuration verified"
}

# ── 6. service ─────────────────────────────────────────────────────────

install_service() {
  step "Installing the termux-services service"
  mkdir -p "$SERVICE_DIR/log" "$LOG_DIR"

  # runit supervises this process, so it must stay in the foreground: no
  # daemonising, no backgrounding, and unbuffered output so logs appear.
  cat > "$SERVICE_DIR/run" <<EOF
#!$PREFIX/bin/sh
# TermuxFM service (generated by install-termux.sh)
exec 2>&1
exec $BIN_PATH serve \\
  --config $CONFIG_PATH \\
  --root $ROOT_DIR \\
  --host $HOST \\
  --port $PORT
EOF
  chmod 755 "$SERVICE_DIR/run"

  cat > "$SERVICE_DIR/log/run" <<EOF
#!$PREFIX/bin/sh
exec svlogd -tt $LOG_DIR
EOF
  chmod 755 "$SERVICE_DIR/log/run"

  # No 'down' file: the service starts on its own once runsvdir scans it, which
  # is what makes it come back after a reboot.
  rm -f "$SERVICE_DIR/down"
  ok "service installed at $SERVICE_DIR"
  ok "logs will be written to $LOG_DIR/current"
}

# ── 7. summary ─────────────────────────────────────────────────────────

lan_ip() {
  python3 - <<'PY'
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
try:
    sock.connect(("192.0.2.1", 9))     # sends nothing; just reads the route
    print(sock.getsockname()[0])
except OSError:
    print("<phone-lan-ip>")
finally:
    sock.close()
PY
}

summary() {
  local ip
  ip="$(lan_ip)"
  printf '\n'
  bold "TermuxFM is installed."
  printf '\n'
  bold "1. Start it"
  info "sv up $SERVICE_NAME"
  info "sv status $SERVICE_NAME"
  printf '\n'
  bold "2. Open it from your computer"
  info "http://$ip:$PORT"
  printf '\n'
  bold "3. Start it automatically after reboot"
  info "Add this line to ~/.termux/boot/start-server.sh, next to your"
  info "other 'sv up' lines:"
  printf '\n'
  info "    sv up $SERVICE_NAME"
  printf '\n'
  bold "Useful commands"
  info "sv down $SERVICE_NAME        # stop"
  info "sv restart $SERVICE_NAME     # restart"
  info "tail -f $LOG_DIR/current"
  info "$SERVICE_NAME passwd         # change the password"
  info "$SERVICE_NAME check          # verify the configuration"
  printf '\n'
  info "Root directory: $ROOT_DIR"
  info "Config file:    $CONFIG_PATH"
  printf '\n'
  warn "This server speaks plain HTTP and has no rate limit on transfers."
  warn "Keep it on your LAN. Do not port-forward it to the internet."
}

usage() {
  cat <<EOF
Usage: ./scripts/install-termux.sh [options]

  --root PATH     directory to expose (default: \$HOME/storage/shared/Server)
  --port PORT     TCP port (default: $DEFAULT_PORT)
  --host ADDR     bind address (default: 0.0.0.0, i.e. reachable on the LAN)
  --config PATH   config file location
  --force-setup   re-run the username/password prompt even if a config exists
  -h, --help      show this help
EOF
}

main() {
  HOST="0.0.0.0"
  PORT="$DEFAULT_PORT"
  while [ $# -gt 0 ]; do
    case "$1" in
      --root)         ROOT_DIR="$2"; shift 2 ;;
      --port)         PORT="$2"; shift 2 ;;
      --host)         HOST="$2"; shift 2 ;;
      --config)       CONFIG_PATH="$2"; shift 2 ;;
      --force-setup)  FORCE_SETUP=1; shift ;;
      -h|--help)      usage; exit 0 ;;
      *)              die "unknown option: $1 (try --help)" ;;
    esac
  done

  bold "TermuxFM installer"
  check_termux
  check_storage
  install_files
  create_tree
  check_port
  configure
  install_service
  summary
}

main "$@"
